### PR TITLE
Remove condition causing panic. Fixes #40

### LINKED ISSUE #40: invalid memory address or nil pointer dereference on query for specific entity.
`mim query --id "http://data.mimiro.io/foo/bar2619968" --via="*" --inverse=true --json`

returns the following:
`[{"id":"@context","namespaces":{}},]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x174ae60]`

seems like a comma is present at the end where it should not be.

### PR DESCRIPTION
**Pull request by andebor**

### CODE REVIEW

File: internal/queries/query_builder.go [hunk 1]
```diff
@@ -99,11 +99,6 @@ func (qb *QueryBuilder) QuerySingle(entityId string) (*api.Entity, error) {
 		return nil, nil
```
Comment (rompetroll) [inline internal/queries/query_builder.go:99]: This should probably be
```
if len(entity) < 2 {
    return nil, errors.New("unexpected response")
}
```

reasoning:
- valid responses always consist of 2 entities: 1. context + 2. the query result
- returning nil,nil indicates that there is nothing wrong. which is not the case here

**Review by rompetroll — APPROVED** [review]
